/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projetofinal2.view;

import br.inatel.projetofinal2.model.Medico;
import br.inatel.projetofinal2.modelDAO.MedicoDAO;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class CadastroMedico extends javax.swing.JFrame {

    String nome;
    String crm;
    int idade;
    String endereco;
    String telefone;
    String email;
    String senha;
    /** Creates new form CadastroMedico */
    public CadastroMedico() {
        initComponents();
        setLocationRelativeTo(null);
        limpar();
        saveButton.setEnabled(true);
        cancelButton.setEnabled(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMedico = new javax.swing.JPanel();
        nMedico = new javax.swing.JLabel();
        campoNomeMedico = new javax.swing.JTextField();
        crmMedico = new javax.swing.JLabel();
        idadeMedico = new javax.swing.JLabel();
        enderecoMedico = new javax.swing.JLabel();
        telefoneMedico = new javax.swing.JLabel();
        emailMedico = new javax.swing.JLabel();
        senhaMedico = new javax.swing.JLabel();
        campoEnderecoMedico = new javax.swing.JTextField();
        campoSenhaMedico = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        campoEmailMedico = new javax.swing.JTextField();
        campoIdadeMedico = new javax.swing.JFormattedTextField();
        campoTelefoneMedico = new javax.swing.JFormattedTextField();
        campoCrmMedico = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true), "Cadastro Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N
        painelMedico.setToolTipText("");

        nMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        nMedico.setText("Nome:");

        campoNomeMedico.setToolTipText("Insira o nome do médico");
        campoNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeMedicoActionPerformed(evt);
            }
        });

        crmMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        crmMedico.setText("CRM:");

        idadeMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        idadeMedico.setText("Idade:");

        enderecoMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        enderecoMedico.setText("Endereço:");

        telefoneMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        telefoneMedico.setText("Telefone:");

        emailMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        emailMedico.setText("E-mail:");

        senhaMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        senhaMedico.setText("Senha:");

        campoEnderecoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoMedicoActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\ProjetosNetBeans\\ProjetoFinal2\\src\\Imagens\\clean2.png")); // NOI18N
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        try {
            campoIdadeMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoIdadeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdadeMedicoActionPerformed(evt);
            }
        });

        try {
            campoTelefoneMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefoneMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneMedicoActionPerformed(evt);
            }
        });

        try {
            campoCrmMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCrmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCrmMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMedicoLayout = new javax.swing.GroupLayout(painelMedico);
        painelMedico.setLayout(painelMedicoLayout);
        painelMedicoLayout.setHorizontalGroup(
            painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelMedicoLayout.createSequentialGroup()
                        .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nMedico)
                            .addComponent(idadeMedico)
                            .addComponent(crmMedico))
                        .addGap(38, 38, 38)
                        .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIdadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelMedicoLayout.createSequentialGroup()
                        .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoMedico)
                            .addComponent(telefoneMedico)
                            .addComponent(emailMedico)
                            .addComponent(senhaMedico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelMedicoLayout.createSequentialGroup()
                                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelMedicoLayout.createSequentialGroup()
                                        .addComponent(campoSenhaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelMedicoLayout.createSequentialGroup()
                                        .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoEnderecoMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                            .addComponent(campoEmailMedico))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(172, 172, 172))
                            .addGroup(painelMedicoLayout.createSequentialGroup()
                                .addComponent(campoTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMedicoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        painelMedicoLayout.setVerticalGroup(
            painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMedicoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crmMedico)
                    .addComponent(campoCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nMedico)
                    .addComponent(campoNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeMedico)
                    .addComponent(campoIdadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoMedico)
                    .addComponent(campoEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailMedico)
                    .addComponent(campoEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoLimpar)
                    .addGroup(painelMedicoLayout.createSequentialGroup()
                        .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoSenhaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaMedico))
                        .addGap(3, 3, 3)))
                .addGap(55, 55, 55)
                .addGroup(painelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeMedicoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoNomeMedicoActionPerformed
     
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        MedicoDAO medDAO = new MedicoDAO();
        boolean check = medDAO.verificaMedico(campoCrmMedico.getText());
        if("".equals(campoNomeMedico.getText()) || "".equals(campoCrmMedico.getText()) 
                || "".equals(campoIdadeMedico.getText()) || "".equals(campoEnderecoMedico.getText()) 
                || "".equals(campoTelefoneMedico.getText()) || "".equals(campoEmailMedico.getText())
                || "".equals(campoSenhaMedico.getText())){
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        }else if(check)
            JOptionPane.showMessageDialog(null, "CRM já cadastrado!");
        else{
            nome = campoNomeMedico.getText();
            crm = campoCrmMedico.getText();
            String idadeAux = campoIdadeMedico.getText();
            idade = Integer.parseInt(idadeAux);
            telefone = campoTelefoneMedico.getText();
            email = campoEmailMedico.getText();
            senha = campoSenhaMedico.getText();
            endereco = campoEnderecoMedico.getText();
            Medico novoMedico = new Medico(crm, nome, idade, endereco, telefone, email, senha);
            medDAO.inserirMedico(novoMedico);
            JOptionPane.showMessageDialog(null, "Médico cadastrado com sucesso!");
            limpar();
           
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        mudarTelaPrincipal();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void campoEnderecoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoMedicoActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void campoTelefoneMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneMedicoActionPerformed

    private void campoIdadeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdadeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdadeMedicoActionPerformed

    private void campoCrmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCrmMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCrmMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JFormattedTextField campoCrmMedico;
    private javax.swing.JTextField campoEmailMedico;
    private javax.swing.JTextField campoEnderecoMedico;
    private javax.swing.JFormattedTextField campoIdadeMedico;
    private javax.swing.JTextField campoNomeMedico;
    private javax.swing.JTextField campoSenhaMedico;
    private javax.swing.JFormattedTextField campoTelefoneMedico;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel crmMedico;
    private javax.swing.JLabel emailMedico;
    private javax.swing.JLabel enderecoMedico;
    private javax.swing.JLabel idadeMedico;
    private javax.swing.JLabel nMedico;
    private javax.swing.JPanel painelMedico;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel senhaMedico;
    private javax.swing.JLabel telefoneMedico;
    // End of variables declaration//GEN-END:variables

private void mudarTelaPrincipal() {
        
        // Criar instancia
        TelaMain tm = new TelaMain();
        // Mostrar a tela
        tm.setVisible(true);
        // Ocultar essa tela
        this.dispose();
        
    }

    public void limpar(){
        campoCrmMedico.setText("");
        campoNomeMedico.setText("");
        campoIdadeMedico.setText("");
        campoEnderecoMedico.setText("");
        campoEmailMedico.setText("");
        campoSenhaMedico.setText("");
        campoTelefoneMedico.setText("");
    }



}
