/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projetofinal2.view;

import br.inatel.projetofinal2.model.Consulta;
import br.inatel.projetofinal2.modelDAO.ConsultaDAO;
import br.inatel.projetofinal2.modelDAO.MedicoDAO;
import br.inatel.projetofinal2.modelDAO.PacienteDAO;
import java.util.ArrayList;
/**
 *
 * @author gabri
 */
public class TelaConsultas extends javax.swing.JFrame {

    /** Creates new form TelaConsultas */
    public TelaConsultas() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarConsultas();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConsultas = new javax.swing.JPanel();
        painelNomeMedico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMedico = new javax.swing.JList();
        painelPaciente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPaciente = new javax.swing.JList();
        painelData = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaData = new javax.swing.JList();
        painelHorario = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaHorario = new javax.swing.JList();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true), "Consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        painelNomeMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jScrollPane1.setViewportView(ListaMedico);

        javax.swing.GroupLayout painelNomeMedicoLayout = new javax.swing.GroupLayout(painelNomeMedico);
        painelNomeMedico.setLayout(painelNomeMedicoLayout);
        painelNomeMedicoLayout.setHorizontalGroup(
            painelNomeMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelNomeMedicoLayout.setVerticalGroup(
            painelNomeMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        painelPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jScrollPane2.setViewportView(listaPaciente);

        javax.swing.GroupLayout painelPacienteLayout = new javax.swing.GroupLayout(painelPaciente);
        painelPaciente.setLayout(painelPacienteLayout);
        painelPacienteLayout.setHorizontalGroup(
            painelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelPacienteLayout.setVerticalGroup(
            painelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        painelData.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jScrollPane3.setViewportView(listaData);

        javax.swing.GroupLayout painelDataLayout = new javax.swing.GroupLayout(painelData);
        painelData.setLayout(painelDataLayout);
        painelDataLayout.setHorizontalGroup(
            painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelDataLayout.setVerticalGroup(
            painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        painelHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Horário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jScrollPane4.setViewportView(listaHorario);

        javax.swing.GroupLayout painelHorarioLayout = new javax.swing.GroupLayout(painelHorario);
        painelHorario.setLayout(painelHorarioLayout);
        painelHorarioLayout.setHorizontalGroup(
            painelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        painelHorarioLayout.setVerticalGroup(
            painelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        botaoVoltar.setBackground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsultasLayout = new javax.swing.GroupLayout(painelConsultas);
        painelConsultas.setLayout(painelConsultasLayout);
        painelConsultasLayout.setHorizontalGroup(
            painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultasLayout.createSequentialGroup()
                .addComponent(painelNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoVoltar)
                .addContainerGap())
        );
        painelConsultasLayout.setVerticalGroup(
            painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsultasLayout.createSequentialGroup()
                        .addComponent(painelHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar))
                    .addGroup(painelConsultasLayout.createSequentialGroup()
                        .addGroup(painelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(painelPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelNomeMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        voltar();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaMedico;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList listaData;
    private javax.swing.JList listaHorario;
    private javax.swing.JList listaPaciente;
    private javax.swing.JPanel painelConsultas;
    private javax.swing.JPanel painelData;
    private javax.swing.JPanel painelHorario;
    private javax.swing.JPanel painelNomeMedico;
    private javax.swing.JPanel painelPaciente;
    // End of variables declaration//GEN-END:variables

    
    
    public void exibirHorario(){
        
        ConsultaDAO cDAO = new ConsultaDAO();
        ArrayList<Consulta> listaConsultas = cDAO.buscaConsultas();
        
        String[] consultas = new String[listaConsultas.size()];
        for (int i = 0; i < consultas.length; i++) {
            consultas[i] = listaConsultas.get(i).getHorario();
          
        }
        listaHorario.setListData(consultas);
        
    }
    
    public void exibirData(){
        
        ConsultaDAO cDAO = new ConsultaDAO();
        ArrayList<Consulta> listaConsultas = cDAO.buscaConsultas();
        
        String[] consultas = new String[listaConsultas.size()];
        for (int i = 0; i < consultas.length; i++) {
            consultas[i] = listaConsultas.get(i).getData();
         
           exibirHorario() ;
          
        }
        listaData.setListData(consultas);
        
    }
    public void exibirCpf(){
        
        ConsultaDAO cDAO = new ConsultaDAO();
        PacienteDAO pDAO = new PacienteDAO();
        
        ArrayList<Consulta> listaConsultas = cDAO.buscaConsultas();
        
        String[] consultas = new String[listaConsultas.size()];
        String[] nomes = new String[listaConsultas.size()];
        for (int i = 0; i < consultas.length; i++) {
            
            consultas[i] = listaConsultas.get(i).getCpfPaciente();
            nomes[i] = pDAO.retornaNomePaciente(consultas[i]);
            exibirData() ;
          
        }
        listaPaciente.setListData(nomes);
        
    }
    public void mostrarConsultas(){
        
        ConsultaDAO cDAO = new ConsultaDAO();
        MedicoDAO mDAO = new MedicoDAO();
        ArrayList<Consulta> listaConsultas = cDAO.buscaConsultas();
        
        String[] consultas = new String[listaConsultas.size()];
        String[] nomes = new String[listaConsultas.size()];
        for (int i = 0; i < consultas.length; i++) {
            consultas[i] = listaConsultas.get(i).getCrmMedico();
            nomes[i] = mDAO.retornaNomeMedico(consultas[i]);
           exibirCpf() ;
        }
        ListaMedico.setListData(nomes);
    }

    public void voltar(){
        
        TelaMain tm = new TelaMain();
        tm.setVisible(true);
        this.dispose();
        
    }
}
