/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.projetofinal2.view;

import br.inatel.projetofinal2.model.Paciente;
import br.inatel.projetofinal2.modelDAO.HistoricoDAO;
import br.inatel.projetofinal2.view.TelaLogin;
import br.inatel.projetofinal2.view.CadastroPaciente;
import br.inatel.projetofinal2.view.CadastroMedico;
import br.inatel.projetofinal2.modelDAO.MedicoDAO;
import br.inatel.projetofinal2.modelDAO.PacienteDAO;
import br.inatel.projetofinal2.modelDAO.SalaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaMain extends javax.swing.JFrame {

    /** Creates new form TelaMain */
    boolean atualizarNomeMedico = false;
    boolean atualizarEnderecoMedico = false;
    boolean atualizarTelefoneMedico = false;
    boolean atualizarIdadeMedico = false;
    boolean atualizarEmailMedico = false;
    boolean atualizarSenhaMedico = false;
    boolean atualizarIdadePaciente = false;
    boolean atualizarNomePaciente = false;
    boolean atualizarEmailPaciente = false;
    boolean atualizarEnderecoPaciente = false;
    boolean atualizarTelefonePaciente = false;
    boolean excluirMedico = false;
    boolean excluirPaciente = false;
    boolean excluirHistorico = false;
    boolean excluirSala = false;
    boolean marcarConsulta = false;
    boolean desmarcarConsulta = false;
    MedicoDAO mDAO;
    PacienteDAO pDAO;
    HistoricoDAO hDAO;
    SalaDAO sDAO;

    public TelaMain() {

        initComponents();
        setLocationRelativeTo(null);
        novaInfoMedico.setText("");
        crmAtualizarMedico.setText("");
        novaInfoPaciente.setText("");
        cpfAtualizarPaciente.setText("");
        campoNovaInfoMedico.setVisible(false);
        campoCrmMedicoAtualizar.setVisible(false);
        botatoConfirmarMudancaMedico.setVisible(false);
        campoNovaInfoPaciente.setVisible(false);
        campoCpfPacienteAtualizar.setVisible(false);
        botaoConfirmarMudancaPaciente.setVisible(false);
        botaoConfirmarExclusao.setVisible(false);
        cpfExcluir.setVisible(false);
        crmExcluir.setVisible(false);
        idExcluir.setVisible(false);
        numeroExcluir.setVisible(false);
        campoExcluirMedico.setVisible(false);
        campoExcluirPaciente.setVisible(false);
        campoExcluirHistorico.setVisible(false);
        campoExcluirSala.setVisible(false);

        mDAO = new MedicoDAO();
        pDAO = new PacienteDAO();
        hDAO = new HistoricoDAO();
        sDAO = new SalaDAO();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botaoCadastroMedico = new javax.swing.JButton();
        botaoCadastroPaciente = new javax.swing.JButton();
        botaoRegistrarHistorico = new javax.swing.JButton();
        botaoAtribuirSala = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoMarcarConsulta = new javax.swing.JButton();
        botaoDesmarcarConsulta = new javax.swing.JButton();
        botaoVerConsultas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        botaoMudarNomeMedico = new javax.swing.JButton();
        botaoMudarEnderecoMedico = new javax.swing.JButton();
        botaoMudarTelefoneMedico = new javax.swing.JButton();
        botaoMudarEmailMedico = new javax.swing.JButton();
        botaoMudarIdadeMedico = new javax.swing.JButton();
        crmAtualizarMedico = new javax.swing.JLabel();
        novoInfoMedico = new javax.swing.JLabel();
        campoNovaInfoMedico = new javax.swing.JTextField();
        novaInfoMedico = new javax.swing.JLabel();
        botaoMudarSenhaMedico = new javax.swing.JButton();
        botatoConfirmarMudancaMedico = new javax.swing.JButton();
        campoCrmMedicoAtualizar = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        botaroMudarNomePaciente = new javax.swing.JButton();
        botaoMudarEnderecoPaciente = new javax.swing.JButton();
        botaoMudarTelefonePaciente = new javax.swing.JButton();
        botaoMudarEmailPaciente = new javax.swing.JButton();
        botaoMudarIdadePaciente = new javax.swing.JButton();
        cpfAtualizarPaciente = new javax.swing.JLabel();
        novaInfoPaciente = new javax.swing.JLabel();
        campoNovaInfoPaciente = new javax.swing.JTextField();
        campoCpfPacienteAtualizar = new javax.swing.JFormattedTextField();
        botaoConfirmarMudancaPaciente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        botaoExcluirMedico = new javax.swing.JButton();
        botaoExcluirPaciente = new javax.swing.JButton();
        campoExcluirMedico = new javax.swing.JFormattedTextField();
        campoExcluirPaciente = new javax.swing.JFormattedTextField();
        crmExcluir = new javax.swing.JLabel();
        cpfExcluir = new javax.swing.JLabel();
        botaoConfirmarExclusao = new javax.swing.JButton();
        botaoExcluirHistorico = new javax.swing.JButton();
        botaoExcluirSala = new javax.swing.JButton();
        idExcluir = new javax.swing.JLabel();
        numeroExcluir = new javax.swing.JLabel();
        campoExcluirHistorico = new javax.swing.JTextField();
        campoExcluirSala = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        botaoInfoMedico = new javax.swing.JButton();
        botaoInfoPaciente = new javax.swing.JButton();
        botaoInfoHistorico = new javax.swing.JButton();
        botaoInfoSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoCadastroMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastroMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoCadastroMedico.setText("Médico");
        botaoCadastroMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCadastroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroMedicoActionPerformed(evt);
            }
        });

        botaoCadastroPaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastroPaciente.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoCadastroPaciente.setText("Paciente");
        botaoCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroPacienteActionPerformed(evt);
            }
        });

        botaoRegistrarHistorico.setBackground(new java.awt.Color(255, 255, 255));
        botaoRegistrarHistorico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoRegistrarHistorico.setText("Registrar Histórico");
        botaoRegistrarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarHistoricoActionPerformed(evt);
            }
        });

        botaoAtribuirSala.setBackground(new java.awt.Color(255, 255, 255));
        botaoAtribuirSala.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoAtribuirSala.setText("Atribuir Sala");
        botaoAtribuirSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtribuirSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastroMedico)
                    .addComponent(botaoCadastroPaciente)
                    .addComponent(botaoRegistrarHistorico)
                    .addComponent(botaoAtribuirSala))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botaoCadastroMedico)
                .addGap(31, 31, 31)
                .addComponent(botaoCadastroPaciente)
                .addGap(29, 29, 29)
                .addComponent(botaoRegistrarHistorico)
                .addGap(28, 28, 28)
                .addComponent(botaoAtribuirSala)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        botaoMarcarConsulta.setBackground(new java.awt.Color(255, 255, 255));
        botaoMarcarConsulta.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoMarcarConsulta.setText("Marcar Consulta");
        botaoMarcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMarcarConsultaActionPerformed(evt);
            }
        });

        botaoDesmarcarConsulta.setBackground(new java.awt.Color(255, 255, 255));
        botaoDesmarcarConsulta.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoDesmarcarConsulta.setText("Desmarcar Consulta");
        botaoDesmarcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesmarcarConsultaActionPerformed(evt);
            }
        });

        botaoVerConsultas.setBackground(new java.awt.Color(255, 255, 255));
        botaoVerConsultas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoVerConsultas.setText("Ver Consultas");
        botaoVerConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDesmarcarConsulta)
                    .addComponent(botaoMarcarConsulta)
                    .addComponent(botaoVerConsultas))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(botaoMarcarConsulta)
                .addGap(53, 53, 53)
                .addComponent(botaoDesmarcarConsulta)
                .addGap(38, 38, 38)
                .addComponent(botaoVerConsultas)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        botaoMudarNomeMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarNomeMedico.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botaoMudarNomeMedico.setText("Nome");
        botaoMudarNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarNomeMedicoActionPerformed(evt);
            }
        });

        botaoMudarEnderecoMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarEnderecoMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarEnderecoMedico.setText("Endereço");
        botaoMudarEnderecoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarEnderecoMedicoActionPerformed(evt);
            }
        });

        botaoMudarTelefoneMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarTelefoneMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarTelefoneMedico.setText("Telefone");
        botaoMudarTelefoneMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarTelefoneMedicoActionPerformed(evt);
            }
        });

        botaoMudarEmailMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarEmailMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarEmailMedico.setText("Email");
        botaoMudarEmailMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarEmailMedicoActionPerformed(evt);
            }
        });

        botaoMudarIdadeMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarIdadeMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarIdadeMedico.setText("Idade");
        botaoMudarIdadeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarIdadeMedicoActionPerformed(evt);
            }
        });

        crmAtualizarMedico.setText("jLabel1");

        novaInfoMedico.setText("jLabel1");

        botaoMudarSenhaMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarSenhaMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarSenhaMedico.setText("Senha");
        botaoMudarSenhaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarSenhaMedicoActionPerformed(evt);
            }
        });

        botatoConfirmarMudancaMedico.setBackground(new java.awt.Color(255, 255, 255));
        botatoConfirmarMudancaMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botatoConfirmarMudancaMedico.setText("Confirmar");
        botatoConfirmarMudancaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botatoConfirmarMudancaMedicoActionPerformed(evt);
            }
        });

        try {
            campoCrmMedicoAtualizar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoMudarNomeMedico)
                    .addComponent(botaoMudarSenhaMedico)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoMudarEnderecoMedico)
                            .addComponent(botaoMudarTelefoneMedico)
                            .addComponent(botaoMudarEmailMedico)
                            .addComponent(botaoMudarIdadeMedico))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(botatoConfirmarMudancaMedico)
                                .addGap(0, 123, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crmAtualizarMedico)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(novaInfoMedico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(novoInfoMedico)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNovaInfoMedico)
                                    .addComponent(campoCrmMedicoAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))))
                .addGap(129, 129, 129))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(botaoMudarNomeMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novoInfoMedico)
                            .addComponent(novaInfoMedico))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(crmAtualizarMedico)
                                .addComponent(campoCrmMedicoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(campoNovaInfoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(botaoMudarEnderecoMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoMudarTelefoneMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoMudarEmailMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoMudarIdadeMedico)
                            .addComponent(botatoConfirmarMudancaMedico))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoMudarSenhaMedico)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Médico", jPanel4);

        botaroMudarNomePaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaroMudarNomePaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaroMudarNomePaciente.setText("Nome");
        botaroMudarNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaroMudarNomePacienteActionPerformed(evt);
            }
        });

        botaoMudarEnderecoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarEnderecoPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarEnderecoPaciente.setText("Endereço");
        botaoMudarEnderecoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarEnderecoPacienteActionPerformed(evt);
            }
        });

        botaoMudarTelefonePaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarTelefonePaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarTelefonePaciente.setText("Telefone");
        botaoMudarTelefonePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarTelefonePacienteActionPerformed(evt);
            }
        });

        botaoMudarEmailPaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarEmailPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarEmailPaciente.setText("Email");
        botaoMudarEmailPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarEmailPacienteActionPerformed(evt);
            }
        });

        botaoMudarIdadePaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoMudarIdadePaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoMudarIdadePaciente.setText("Idade");
        botaoMudarIdadePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarIdadePacienteActionPerformed(evt);
            }
        });

        cpfAtualizarPaciente.setText("jLabel1");

        novaInfoPaciente.setText("jLabel2");

        try {
            campoCpfPacienteAtualizar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoConfirmarMudancaPaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoConfirmarMudancaPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoConfirmarMudancaPaciente.setText("Confirmar");
        botaoConfirmarMudancaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarMudancaPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoMudarEnderecoPaciente)
                            .addComponent(botaoMudarTelefonePaciente)
                            .addComponent(botaoMudarEmailPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(novaInfoPaciente)
                                    .addComponent(cpfAtualizarPaciente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoCpfPacienteAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(campoNovaInfoPaciente)))
                            .addComponent(botaoConfirmarMudancaPaciente))
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaroMudarNomePaciente)
                            .addComponent(botaoMudarIdadePaciente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(botaroMudarNomePaciente)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMudarEnderecoPaciente)
                    .addComponent(cpfAtualizarPaciente)
                    .addComponent(campoCpfPacienteAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMudarTelefonePaciente)
                    .addComponent(novaInfoPaciente)
                    .addComponent(campoNovaInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMudarEmailPaciente)
                    .addComponent(botaoConfirmarMudancaPaciente))
                .addGap(21, 21, 21)
                .addComponent(botaoMudarIdadePaciente)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Paciente", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Atualizações", jPanel3);

        botaoExcluirMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoExcluirMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoExcluirMedico.setText("Médico");
        botaoExcluirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirMedicoActionPerformed(evt);
            }
        });

        botaoExcluirPaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoExcluirPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoExcluirPaciente.setText("Paciente");
        botaoExcluirPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirPacienteActionPerformed(evt);
            }
        });

        try {
            campoExcluirMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campoExcluirPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        crmExcluir.setText("jLabel1");

        cpfExcluir.setText("jLabel2");

        botaoConfirmarExclusao.setBackground(new java.awt.Color(255, 255, 255));
        botaoConfirmarExclusao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoConfirmarExclusao.setText("Confirmar");
        botaoConfirmarExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarExclusaoActionPerformed(evt);
            }
        });

        botaoExcluirHistorico.setBackground(new java.awt.Color(255, 255, 255));
        botaoExcluirHistorico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoExcluirHistorico.setText("Histórico");
        botaoExcluirHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirHistoricoActionPerformed(evt);
            }
        });

        botaoExcluirSala.setBackground(new java.awt.Color(255, 255, 255));
        botaoExcluirSala.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoExcluirSala.setText("Sala");
        botaoExcluirSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirSalaActionPerformed(evt);
            }
        });

        idExcluir.setText("jLabel1");

        numeroExcluir.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoExcluirPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(botaoExcluirMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfExcluir)
                            .addComponent(crmExcluir))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoExcluirSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoExcluirHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numeroExcluir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 218, Short.MAX_VALUE)
                        .addComponent(botaoConfirmarExclusao)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoExcluirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoExcluirMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoExcluirHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoExcluirSala, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirMedico)
                    .addComponent(crmExcluir)
                    .addComponent(campoExcluirMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoExcluirPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfExcluir)
                    .addComponent(botaoExcluirPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirHistorico)
                    .addComponent(idExcluir)
                    .addComponent(campoExcluirHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirSala)
                    .addComponent(numeroExcluir)
                    .addComponent(campoExcluirSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(botaoConfirmarExclusao)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Excluir", jPanel6);

        botaoInfoMedico.setBackground(new java.awt.Color(255, 255, 255));
        botaoInfoMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoInfoMedico.setText("Médico");
        botaoInfoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInfoMedicoActionPerformed(evt);
            }
        });

        botaoInfoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        botaoInfoPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoInfoPaciente.setText("Paciente");
        botaoInfoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInfoPacienteActionPerformed(evt);
            }
        });

        botaoInfoHistorico.setBackground(new java.awt.Color(255, 255, 255));
        botaoInfoHistorico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoInfoHistorico.setText("Histórico");
        botaoInfoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInfoHistoricoActionPerformed(evt);
            }
        });

        botaoInfoSala.setBackground(new java.awt.Color(255, 255, 255));
        botaoInfoSala.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoInfoSala.setText("Sala");
        botaoInfoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInfoSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoInfoHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoInfoSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoInfoMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoInfoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(botaoInfoMedico)
                .addGap(18, 18, 18)
                .addComponent(botaoInfoPaciente)
                .addGap(18, 18, 18)
                .addComponent(botaoInfoHistorico)
                .addGap(18, 18, 18)
                .addComponent(botaoInfoSala)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informações", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirSalaActionPerformed
        // TODO add your handling code here:
        campoExcluirMedico.setVisible(false);
        campoExcluirPaciente.setVisible(false);
        campoExcluirHistorico.setVisible(false);
        campoExcluirSala.setVisible(true);
        crmExcluir.setVisible(false);
        cpfExcluir.setVisible(false);
        idExcluir.setVisible(false);
        numeroExcluir.setVisible(true);
        botaoConfirmarExclusao.setVisible(true);
        numeroExcluir.setText("Número: ");
        excluirPaciente = false;
        excluirMedico = false;
        excluirHistorico = false;
        excluirSala = true;
        limparExclusao();
    }//GEN-LAST:event_botaoExcluirSalaActionPerformed

    private void botaoExcluirHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirHistoricoActionPerformed
        // TODO add your handling code here:
        campoExcluirMedico.setVisible(false);
        campoExcluirPaciente.setVisible(false);
        campoExcluirHistorico.setVisible(true);
        campoExcluirSala.setVisible(false);
        crmExcluir.setVisible(false);
        cpfExcluir.setVisible(false);
        idExcluir.setVisible(true);
        numeroExcluir.setVisible(false);
        botaoConfirmarExclusao.setVisible(true);
        idExcluir.setText("ID: ");
        excluirPaciente = false;
        excluirMedico = false;
        excluirHistorico = true;
        excluirSala = false;
        limparExclusao();
    }//GEN-LAST:event_botaoExcluirHistoricoActionPerformed

    private void botaoConfirmarExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarExclusaoActionPerformed
        // TODO add your handling code here:
        confirmarExclusao();
    }//GEN-LAST:event_botaoConfirmarExclusaoActionPerformed

    private void botaoExcluirPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirPacienteActionPerformed
        // TODO add your handling code here:
        campoExcluirMedico.setVisible(false);
        campoExcluirPaciente.setVisible(true);
        campoExcluirHistorico.setVisible(false);
        campoExcluirSala.setVisible(false);
        crmExcluir.setVisible(false);
        cpfExcluir.setVisible(true);
        idExcluir.setVisible(false);
        numeroExcluir.setVisible(false);
        botaoConfirmarExclusao.setVisible(true);
        cpfExcluir.setText("CPF: ");
        excluirPaciente = true;
        excluirMedico = false;
        excluirHistorico = false;
        excluirSala = false;
        limparExclusao();
    }//GEN-LAST:event_botaoExcluirPacienteActionPerformed

    private void botaoExcluirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirMedicoActionPerformed
        // TODO add your handling code here:
        campoExcluirMedico.setVisible(true);
        campoExcluirPaciente.setVisible(false);
        campoExcluirHistorico.setVisible(false);
        campoExcluirSala.setVisible(false);
        crmExcluir.setVisible(true);
        cpfExcluir.setVisible(false);
        idExcluir.setVisible(false);
        numeroExcluir.setVisible(false);
        botaoConfirmarExclusao.setVisible(true);
        crmExcluir.setText("CRM: ");
        excluirPaciente = false;
        excluirMedico = true;
        excluirHistorico = false;
        excluirSala = false;
        limparExclusao();
    }//GEN-LAST:event_botaoExcluirMedicoActionPerformed

    private void botaoConfirmarMudancaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarMudancaPacienteActionPerformed
        // TODO add your handling code here:
        confirmarAtualizacaoPaciente();
    }//GEN-LAST:event_botaoConfirmarMudancaPacienteActionPerformed

    private void botaoMudarIdadePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarIdadePacienteActionPerformed
        // TODO add your handling code here:
        novaInfoPaciente.setText("Nova idade: ");
        cpfAtualizarPaciente.setText("CPF: ");
        campoNovaInfoPaciente.setVisible(true);
        campoCpfPacienteAtualizar.setVisible(true);
        atualizarNomePaciente = false;
        atualizarIdadePaciente = true;
        atualizarEmailPaciente = false;
        atualizarEnderecoPaciente = false;
        atualizarTelefonePaciente = false;
        botaoConfirmarMudancaPaciente.setVisible(true);
        limparPaciente();
    }//GEN-LAST:event_botaoMudarIdadePacienteActionPerformed

    private void botaoMudarEmailPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarEmailPacienteActionPerformed
        // TODO add your handling code here:
        novaInfoPaciente.setText("Novo email: ");
        cpfAtualizarPaciente.setText("CPF: ");
        campoNovaInfoPaciente.setVisible(true);
        campoCpfPacienteAtualizar.setVisible(true);
        atualizarNomePaciente = false;
        atualizarIdadePaciente = false;
        atualizarEmailPaciente = true;
        atualizarEnderecoPaciente = false;
        atualizarTelefonePaciente = false;
        botaoConfirmarMudancaPaciente.setVisible(true);
        limparPaciente();
    }//GEN-LAST:event_botaoMudarEmailPacienteActionPerformed

    private void botaoMudarTelefonePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarTelefonePacienteActionPerformed
        // TODO add your handling code here:
        novaInfoPaciente.setText("Novo telefone: ");
        cpfAtualizarPaciente.setText("CPF: ");
        campoNovaInfoPaciente.setVisible(true);
        campoCpfPacienteAtualizar.setVisible(true);
        atualizarNomePaciente = false;
        atualizarIdadePaciente = false;
        atualizarEmailPaciente = false;
        atualizarEnderecoPaciente = false;
        atualizarTelefonePaciente = true;
        botaoConfirmarMudancaPaciente.setVisible(true);
        limparPaciente();
    }//GEN-LAST:event_botaoMudarTelefonePacienteActionPerformed

    private void botaoMudarEnderecoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarEnderecoPacienteActionPerformed
        // TODO add your handling code here:
        novaInfoPaciente.setText("Novo endereço: ");
        cpfAtualizarPaciente.setText("CPF: ");
        campoNovaInfoPaciente.setVisible(true);
        campoCpfPacienteAtualizar.setVisible(true);
        atualizarNomePaciente = false;
        atualizarIdadePaciente = false;
        atualizarEmailPaciente = false;
        atualizarEnderecoPaciente = true;
        atualizarTelefonePaciente = false;
        botaoConfirmarMudancaPaciente.setVisible(true);
        limparPaciente();
    }//GEN-LAST:event_botaoMudarEnderecoPacienteActionPerformed

    private void botaroMudarNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaroMudarNomePacienteActionPerformed
        // TODO add your handling code here:
        novaInfoPaciente.setText("Novo nome: ");
        cpfAtualizarPaciente.setText("CPF: ");
        campoNovaInfoPaciente.setVisible(true);
        campoCpfPacienteAtualizar.setVisible(true);
        atualizarNomePaciente = true;
        atualizarIdadePaciente = false;
        atualizarEmailPaciente = false;
        atualizarEnderecoPaciente = false;
        atualizarTelefonePaciente = false;
        botaoConfirmarMudancaPaciente.setVisible(true);
        limparPaciente();
    }//GEN-LAST:event_botaroMudarNomePacienteActionPerformed

    private void botatoConfirmarMudancaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botatoConfirmarMudancaMedicoActionPerformed
        // TODO add your handling code here:
        confirmarAtualizacaoMedico();
    }//GEN-LAST:event_botatoConfirmarMudancaMedicoActionPerformed

    private void botaoMudarSenhaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarSenhaMedicoActionPerformed
        // TODO add your handling code here:
        novaInfoMedico.setText("Nova senha: ");
        crmAtualizarMedico.setText("CRM: ");
        campoNovaInfoMedico.setVisible(true);
        campoCrmMedicoAtualizar.setVisible(true);
        atualizarNomeMedico = false;
        atualizarIdadeMedico = false;
        atualizarEmailMedico = false;
        atualizarEnderecoMedico = false;
        atualizarSenhaMedico = true;
        atualizarTelefoneMedico = false;
        botatoConfirmarMudancaMedico.setVisible(true);
        limparMedico();
    }//GEN-LAST:event_botaoMudarSenhaMedicoActionPerformed

    private void botaoMudarIdadeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarIdadeMedicoActionPerformed
        // TODO add your handling code here:
        novaInfoMedico.setText("Nova idade: ");
        crmAtualizarMedico.setText("CRM: ");
        campoNovaInfoMedico.setVisible(true);
        campoCrmMedicoAtualizar.setVisible(true);
        atualizarNomeMedico = false;
        atualizarIdadeMedico = true;
        atualizarEmailMedico = false;
        atualizarEnderecoMedico = false;
        atualizarSenhaMedico = false;
        atualizarTelefoneMedico = false;
        botatoConfirmarMudancaMedico.setVisible(true);
        limparMedico();
    }//GEN-LAST:event_botaoMudarIdadeMedicoActionPerformed

    private void botaoMudarEmailMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarEmailMedicoActionPerformed
        // TODO add your handling code here:
        novaInfoMedico.setText("Novo email: ");
        crmAtualizarMedico.setText("CRM: ");
        campoNovaInfoMedico.setVisible(true);
        campoCrmMedicoAtualizar.setVisible(true);
        atualizarNomeMedico = false;
        atualizarIdadeMedico = false;
        atualizarEmailMedico = true;
        atualizarEnderecoMedico = false;
        atualizarSenhaMedico = false;
        atualizarTelefoneMedico = false;
        botatoConfirmarMudancaMedico.setVisible(true);
        limparMedico();
    }//GEN-LAST:event_botaoMudarEmailMedicoActionPerformed

    private void botaoMudarTelefoneMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarTelefoneMedicoActionPerformed
        // TODO add your handling code here:
        novaInfoMedico.setText("Novo telefone: ");
        crmAtualizarMedico.setText("CRM: ");
        campoNovaInfoMedico.setVisible(true);
        campoCrmMedicoAtualizar.setVisible(true);
        atualizarNomeMedico = false;
        atualizarIdadeMedico = false;
        atualizarEmailMedico = false;
        atualizarEnderecoMedico = false;
        atualizarSenhaMedico = false;
        atualizarTelefoneMedico = true;
        botatoConfirmarMudancaMedico.setVisible(true);
        limparMedico();
    }//GEN-LAST:event_botaoMudarTelefoneMedicoActionPerformed

    private void botaoMudarEnderecoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarEnderecoMedicoActionPerformed
        // TODO add your handling code here:
        novaInfoMedico.setText("Novo endereço: ");
        crmAtualizarMedico.setText("CRM: ");
        campoNovaInfoMedico.setVisible(true);
        campoCrmMedicoAtualizar.setVisible(true);
        atualizarNomeMedico = false;
        atualizarIdadeMedico = false;
        atualizarEmailMedico = false;
        atualizarEnderecoMedico = true;
        atualizarSenhaMedico = false;
        atualizarTelefoneMedico = false;
        botatoConfirmarMudancaMedico.setVisible(true);
        limparMedico();
    }//GEN-LAST:event_botaoMudarEnderecoMedicoActionPerformed

    private void botaoMudarNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarNomeMedicoActionPerformed
        // TODO add your handling code here:
        novaInfoMedico.setText("Novo nome: ");
        crmAtualizarMedico.setText("CRM: ");
        campoNovaInfoMedico.setVisible(true);
        campoCrmMedicoAtualizar.setVisible(true);
        atualizarNomeMedico = true;
        atualizarIdadeMedico = false;
        atualizarEmailMedico = false;
        atualizarEnderecoMedico = false;
        atualizarSenhaMedico = false;
        atualizarTelefoneMedico = false;
        botatoConfirmarMudancaMedico.setVisible(true);
        limparMedico();
    }//GEN-LAST:event_botaoMudarNomeMedicoActionPerformed

    private void botaoVerConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerConsultasActionPerformed
        // TODO add your handling code here:
        telaConsultas();
    }//GEN-LAST:event_botaoVerConsultasActionPerformed

    private void botaoDesmarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesmarcarConsultaActionPerformed
        // TODO add your handling code here:
        mudarTelaLogin2();
    }//GEN-LAST:event_botaoDesmarcarConsultaActionPerformed

    private void botaoMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMarcarConsultaActionPerformed
        // TODO add your handling code here:
        mudarTelaLogin1();
    }//GEN-LAST:event_botaoMarcarConsultaActionPerformed

    private void botaoAtribuirSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtribuirSalaActionPerformed
        // TODO add your handling code here:
        atribuirSala();
    }//GEN-LAST:event_botaoAtribuirSalaActionPerformed

    private void botaoRegistrarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarHistoricoActionPerformed
        // TODO add your handling code here:
        mudarRegistroHistorico();
    }//GEN-LAST:event_botaoRegistrarHistoricoActionPerformed

    private void botaoCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroPacienteActionPerformed
        // TODO add your handling code here:
        mudarCadastroPaciente();
    }//GEN-LAST:event_botaoCadastroPacienteActionPerformed

    private void botaoCadastroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroMedicoActionPerformed
        // TODO add your handling code here:
        mudarCadastroMedico();
    }//GEN-LAST:event_botaoCadastroMedicoActionPerformed

    private void botaoInfoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInfoMedicoActionPerformed
        // TODO add your handling code here:
        infoMedico();
    }//GEN-LAST:event_botaoInfoMedicoActionPerformed

    private void botaoInfoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInfoPacienteActionPerformed
        // TODO add your handling code here:
        infoPaciente();
    }//GEN-LAST:event_botaoInfoPacienteActionPerformed

    private void botaoInfoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInfoHistoricoActionPerformed
        // TODO add your handling code here:
        infoHistorico();
    }//GEN-LAST:event_botaoInfoHistoricoActionPerformed

    private void botaoInfoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInfoSalaActionPerformed
        // TODO add your handling code here:
        infoSala();
    }//GEN-LAST:event_botaoInfoSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtribuirSala;
    private javax.swing.JButton botaoCadastroMedico;
    private javax.swing.JButton botaoCadastroPaciente;
    private javax.swing.JButton botaoConfirmarExclusao;
    private javax.swing.JButton botaoConfirmarMudancaPaciente;
    private javax.swing.JButton botaoDesmarcarConsulta;
    private javax.swing.JButton botaoExcluirHistorico;
    private javax.swing.JButton botaoExcluirMedico;
    private javax.swing.JButton botaoExcluirPaciente;
    private javax.swing.JButton botaoExcluirSala;
    private javax.swing.JButton botaoInfoHistorico;
    private javax.swing.JButton botaoInfoMedico;
    private javax.swing.JButton botaoInfoPaciente;
    private javax.swing.JButton botaoInfoSala;
    private javax.swing.JButton botaoMarcarConsulta;
    private javax.swing.JButton botaoMudarEmailMedico;
    private javax.swing.JButton botaoMudarEmailPaciente;
    private javax.swing.JButton botaoMudarEnderecoMedico;
    private javax.swing.JButton botaoMudarEnderecoPaciente;
    private javax.swing.JButton botaoMudarIdadeMedico;
    private javax.swing.JButton botaoMudarIdadePaciente;
    private javax.swing.JButton botaoMudarNomeMedico;
    private javax.swing.JButton botaoMudarSenhaMedico;
    private javax.swing.JButton botaoMudarTelefoneMedico;
    private javax.swing.JButton botaoMudarTelefonePaciente;
    private javax.swing.JButton botaoRegistrarHistorico;
    private javax.swing.JButton botaoVerConsultas;
    private javax.swing.JButton botaroMudarNomePaciente;
    private javax.swing.JButton botatoConfirmarMudancaMedico;
    private javax.swing.JFormattedTextField campoCpfPacienteAtualizar;
    private javax.swing.JFormattedTextField campoCrmMedicoAtualizar;
    private javax.swing.JTextField campoExcluirHistorico;
    private javax.swing.JFormattedTextField campoExcluirMedico;
    private javax.swing.JFormattedTextField campoExcluirPaciente;
    private javax.swing.JTextField campoExcluirSala;
    private javax.swing.JTextField campoNovaInfoMedico;
    private javax.swing.JTextField campoNovaInfoPaciente;
    private javax.swing.JLabel cpfAtualizarPaciente;
    private javax.swing.JLabel cpfExcluir;
    private javax.swing.JLabel crmAtualizarMedico;
    private javax.swing.JLabel crmExcluir;
    private javax.swing.JLabel idExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel novaInfoMedico;
    private javax.swing.JLabel novaInfoPaciente;
    private javax.swing.JLabel novoInfoMedico;
    private javax.swing.JLabel numeroExcluir;
    // End of variables declaration//GEN-END:variables

    public void atribuirSala() {

        AtribuirSala as = new AtribuirSala();
        as.setVisible(true);
        this.dispose();

    }

    public void confirmarExclusao() {

        boolean check1 = checarMedico();
        boolean check2 = checarPaciente();
        boolean check3 = checarHistorico();
        boolean check4 = checarSala();

        if (excluirMedico) {

            if (!check1) {
                JOptionPane.showMessageDialog(null, "Entre com CRM válido!");
            } else {

                mDAO.excluirMedico(campoExcluirMedico.getText());

                JOptionPane.showMessageDialog(null, "Médico excluído com sucesso!");
            }

        } else if (excluirPaciente) {

           if (!check2) {
                JOptionPane.showMessageDialog(null, "Entre com CPF válido!");
            } else {

                pDAO.excluirPaciente(campoExcluirPaciente.getText());

                JOptionPane.showMessageDialog(null, "Paciente excluído com sucesso!");
            }
        }else if(excluirHistorico){
            
            if (!check3) {
                JOptionPane.showMessageDialog(null, "Entre com ID válido!");
            } else {

                hDAO.excluirHistorico(campoExcluirHistorico.getText());

                JOptionPane.showMessageDialog(null, "Historico excluído com sucesso!");
            }
            
        }else if(excluirSala){
            
            if (!check4) {
                JOptionPane.showMessageDialog(null, "Entre com Número válido!");
            } else {

                sDAO.excluirSala(campoExcluirSala.getText());

                JOptionPane.showMessageDialog(null, "Sala excluída com sucesso!");
            }
            
            
        }
        
        limparExclusao();

    }

    public void confirmarAtualizacaoMedico() {

        boolean check = mDAO.verificaMedico(campoCrmMedicoAtualizar.getText());
        if (!check) {
            JOptionPane.showMessageDialog(null, "Digite um CRM válido!");
        } else if ("".equals(campoCrmMedicoAtualizar.getText()) || "".equals(campoNovaInfoMedico.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        } else if (atualizarNomeMedico) {

            mDAO.alterarNomeMedico(campoCrmMedicoAtualizar.getText(), campoNovaInfoMedico.getText());
            atualizacaoMensagem();

        } else if (atualizarIdadeMedico) {

            int i = getIdade();
            mDAO.alterarIdadeMedico(campoCrmMedicoAtualizar.getText(), i);
            atualizacaoMensagem();

        } else if (atualizarEmailMedico) {

            mDAO.alterarEmailMedico(campoCrmMedicoAtualizar.getText(), campoNovaInfoMedico.getText());
            atualizacaoMensagem();
        } else if (atualizarTelefoneMedico) {

            mDAO.alterarTelefoneMedico(campoCrmMedicoAtualizar.getText(), campoNovaInfoMedico.getText());
            atualizacaoMensagem();

        } else if (atualizarSenhaMedico) {

            mDAO.alterarSenhaMedico(campoCrmMedicoAtualizar.getText(), campoNovaInfoMedico.getText());
            atualizacaoMensagem();

        } else if (atualizarEnderecoMedico) {

            mDAO.alterarEnderecoMedico(campoCrmMedicoAtualizar.getText(), campoNovaInfoMedico.getText());
            atualizacaoMensagem();

        }

    }

    public void confirmarAtualizacaoPaciente() {
        
        boolean check = pDAO.verificaPaciente(campoCpfPacienteAtualizar.getText());
        if (!check) {
            JOptionPane.showMessageDialog(null, "Digite um CPF válido!");
        } else if ("".equals(campoCpfPacienteAtualizar.getText()) || "".equals(campoNovaInfoPaciente.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        } else if (atualizarNomePaciente) {

            pDAO.alterarNomePaciente(campoCpfPacienteAtualizar.getText(), campoNovaInfoPaciente.getText());
            atualizacaoMensagem();

        } else if (atualizarIdadePaciente) {

            int i = getIdade();
            pDAO.alterarIdadePaciente(campoCpfPacienteAtualizar.getText(), i);
            atualizacaoMensagem();

        } else if (atualizarEmailPaciente) {

            pDAO.alterarEmailPaciente(campoCpfPacienteAtualizar.getText(), campoNovaInfoPaciente.getText());
            atualizacaoMensagem();
        } else if (atualizarTelefonePaciente) {

            pDAO.alterarTelefonePaciente(campoCpfPacienteAtualizar.getText(), campoNovaInfoPaciente.getText());
            atualizacaoMensagem();
        } else if (atualizarEnderecoPaciente) {

            pDAO.alterarEnderecoPaciente(campoCpfPacienteAtualizar.getText(), campoNovaInfoPaciente.getText());
            atualizacaoMensagem();

        }

    }

    public void mudarCadastroMedico() {
        CadastroMedico cm = new CadastroMedico();
        cm.setVisible(true);
        this.dispose();
    }

    public void mudarCadastroPaciente() {
        CadastroPaciente cp = new CadastroPaciente();
        cp.setVisible(true);
        this.dispose();
    }

    public void telaConsultas() {

        TelaConsultas tc = new TelaConsultas();
        tc.setVisible(true);
        this.dispose();
    }

    public void mudarTelaLogin1() {
        TelaLogin lg = new TelaLogin();
        lg.setVisible(true);
        this.dispose();
    }
    
     public void mudarTelaLogin2() {
        TelaLogin2 lg = new TelaLogin2();
        lg.setVisible(true);
        this.dispose();
    }

    public int getIdade() {

        int c;
        String idadeAux = campoNovaInfoMedico.getText();
        c = Integer.parseInt(idadeAux);
        return c;
    }

    public void limparMedico() {

        campoCrmMedicoAtualizar.setText("");
        campoNovaInfoMedico.setText("");
    }

    public void limparPaciente() {

        campoCpfPacienteAtualizar.setText("");
        campoNovaInfoPaciente.setText("");
    }

    public void limparExclusao() {

        campoExcluirMedico.setText("");
        campoExcluirPaciente.setText("");
        campoExcluirSala.setText("");
        campoExcluirHistorico.setText("");
    }

    public void atualizacaoMensagem() {

        JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
    }

    public boolean checarMedico() {

        MedicoDAO mDAO = new MedicoDAO();
        boolean check = mDAO.verificaMedico(campoExcluirMedico.getText());
        return check;
    }

    public boolean checarPaciente() {

        PacienteDAO pDAO = new PacienteDAO();
        boolean check = pDAO.verificaPaciente(campoExcluirPaciente.getText());
        return check;
    }

    public boolean checarHistorico() {

        HistoricoDAO hDAO = new HistoricoDAO();
        boolean check = hDAO.verificaId(campoExcluirHistorico.getText());
        return check;
    }

    public boolean checarSala() {

        SalaDAO sDAO = new SalaDAO();
        boolean check = sDAO.verificaNumero(campoExcluirSala.getText());
        return check;
    }

    public void mudarRegistroHistorico() {

        RegistroHistorico rh = new RegistroHistorico();
        rh.setVisible(true);
        this.dispose();
    }
    
    public void infoMedico(){
        
        InfoMedico im = new InfoMedico();
        im.setVisible(true);
        this.dispose();
        
    }
    
    public void infoPaciente(){
        
        InfoPaciente ip = new InfoPaciente();
        ip.setVisible(true);
        this.dispose();
    }
    
    public void infoHistorico(){
        
        InfoHistorico ih = new InfoHistorico();
        ih.setVisible(true);
        this.dispose();
    }
    
    public void infoSala(){
        
        InfoSala is = new InfoSala();
        is.setVisible(true);
        this.dispose();
    }

}
